// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wypozyczalnia_Samochodow.Data;

#nullable disable

namespace Wypozyczalnia_Samochodow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Klient", b =>
                {
                    b.Property<int>("IdKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKlienta"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrPrawaJazdy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdKlienta");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Platnosc", b =>
                {
                    b.Property<int>("IdPlatnosci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlatnosci"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WypozyczenieId")
                        .HasColumnType("int");

                    b.HasKey("IdPlatnosci");

                    b.HasIndex("WypozyczenieId")
                        .IsUnique();

                    b.ToTable("Platnosci");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Samochod", b =>
                {
                    b.Property<int>("IdSamochodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSamochodu"));

                    b.Property<decimal>("CenaZaDzien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Dostepny")
                        .HasColumnType("bit");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rejestracja")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.HasKey("IdSamochodu");

                    b.ToTable("Samochody");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("IdWypozyczenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWypozyczenia"));

                    b.Property<decimal>("CenaCalkowita")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("SamochodId")
                        .HasColumnType("int");

                    b.HasKey("IdWypozyczenia");

                    b.HasIndex("KlientId");

                    b.HasIndex("SamochodId");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Platnosc", b =>
                {
                    b.HasOne("Wypozyczalnia_Samochodow.Models.Wypozyczenie", "Wypozyczenie")
                        .WithOne("Platnosc")
                        .HasForeignKey("Wypozyczalnia_Samochodow.Models.Platnosc", "WypozyczenieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wypozyczenie");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Wypozyczenie", b =>
                {
                    b.HasOne("Wypozyczalnia_Samochodow.Models.Klient", "Klient")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wypozyczalnia_Samochodow.Models.Samochod", "Samochod")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("SamochodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Samochod");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Klient", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Samochod", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("Wypozyczalnia_Samochodow.Models.Wypozyczenie", b =>
                {
                    b.Navigation("Platnosc")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
